#pragma once
#include <vector>
#include <string>

namespace Database {
    struct ItemEntry {
        const char* Name;
        const char* ID;
    };

    struct CategoryEntry {
        const char* Name;
        std::vector<ItemEntry> Items;
    };

    static const std::vector<CategoryEntry> Categories = {
        { "Accessories", {
            { "Attack Pendant", "Accessory_AT_1" },
            { "Attack Pendant+1", "Accessory_AT_2" },
            { "Attack Pendant+2", "Accessory_AT_3" },
            { "Defense Pendant", "Accessory_defense_1" },
            { "Defense Pendant +1", "Accessory_defense_2" },
            { "Defense Pendant +2", "Accessory_defense_3" },
            { "Heat Resistant Underwear", "Accessory_HeatResist_1" },
            { "Heat Resistant Underwear+1", "Accessory_HeatResist_2" },
            { "Heat Resistant Underwear+2", "Accessory_HeatResist_3" },
            { "Life Pendant", "Accessory_HP_1" },
            { "Life Pendant+1", "Accessory_HP_2" },
            { "Life Pendant+2", "Accessory_HP_3" },
            { "Pendant Of Diligence", "Accessory_WorkSpeed_1" },
            { "Pendant Of Diligence+1", "Accessory_WorkSpeed_2" },
            { "Pendant Of Diligence+2", "Accessory_WorkSpeed_3" },
            { "Ring Of Water Resistance", "Accessory_AquaResist_1" },
            { "Ring Of Water Resistance+1", "Accessory_AquaResist_2" },
            { "Ring Of Water Resistance+2", "Accessory_AquaResist_3" },
            { "Ring Of Dark Resistance", "Accessory_DarkResist_1" },
            { "Ring Of Dark Resistance+1", "Accessory_DarkResist_2" },
            { "Ring Of Dark Resistance+2", "Accessory_DarkResist_3" },
            { "Ring Of Dragon Resistance", "Accessory_DragonResist_1" },
            { "Ring Of Dragon Resistance+1", "Accessory_DragonResist_2" },
            { "Ring Of Dragon Resistance+2", "Accessory_DragonResist_3" },
            { "Ring Of Earth Resistance", "Accessory_EarthResist_1" },
            { "Ring Of Earth Resistance+1", "Accessory_EarthResist_2" },
            { "Ring Of Earth Resistance+2", "Accessory_EarthResist_3" },
            { "Ring Of Flame Resistance", "Accessory_FireResist_1" },
            { "Ring Of Flame Resistance+1", "Accessory_FireResist_2" },
            { "Ring Of Flame Resistance+2", "Accessory_FireResist_3" },
            { "Ring Of Ice Resistance", "Accessory_IceResist_1" },
            { "Ring Of Ice Resistance+1", "Accessory_IceResist_2" },
            { "Ring Of Ice Resistance+2", "Accessory_IceResist_3" },
            { "Ring Of Grass Resistance", "Accessory_LeafResist_1" },
            { "Ring Of Grass Resistance+1", "Accessory_LeafResist_2" },
            { "Ring Of Grass Resistance+2", "Accessory_LeafResist_3" },
            { "Ring Of Resistance", "Accessory_NormalResist_1" },
            { "Ring Of Resistance+1", "Accessory_NormalResist_2" },
            { "Ring Of Resistance+2", "Accessory_NormalResist_3" },
            { "Ring Of Lightning Resistance", "Accessory_ThunderResist_1" },
            { "Ring Of Lightning Resistance+1", "Accessory_ThunderResist_2" },
            { "Ring Of Lightning Resistance+2", "Accessory_ThunderResist_3" },
            { "Thermal Underwear", "Accessory_CoolResist_1" },
            { "Thermal Underwear+1", "Accessory_CoolResist_2" },
            { "Thermal Underwear+2", "Accessory_CoolResist_3" },
            { "Air Dash Boots I", "Accessory_AirDash1" },
            { "Air Dash Boots II", "Accessory_AirDash2" },
            { "Air Dash Boots III", "Accessory_AirDash3" },
            { "Air Dash Boots IV", "Accessory_AirDash4" },
            { "Double Jump Boots", "Accessory_JumpCount_Increase1" },
            { "Triple Jump Boots", "Accessory_JumpCount_Increase2" },
            { "Quad Jump Boots", "Accessory_JumpCount_Increase3" },
            { "Anti-Gravity Belt", "Accessory_JumpPower_Increase" },
            { "Small Expansion Backpack", "AdditionalInventory_001" },
            { "Medium Expansion Backpack", "AdditionalInventory_002" },
            { "Large Expansion Backpack", "AdditionalInventory_003" },
            { "Giant Expansion Backpack", "AdditionalInventory_004" },
            { "Neutral Element Whistle (Common)", "Otomo_ElementBoost_Normal_1" },
            { "Fire Element Whistle (Common)", "Otomo_ElementBoost_Fire_1" },
            { "Water Element Whistle (Common)", "Otomo_ElementBoost_Water_1" },
            { "Electric Element Whistle (Common)", "Otomo_ElementBoost_Electricity_1" },
            { "Leaf Element Whistle (Common)", "Otomo_ElementBoost_Leaf_1" },
            { "Ice Element Whistle (Common)", "Otomo_ElementBoost_Ice_1" },
            { "Defense Support Whistle +2 (Rare)", "Otomo_Defense_up3" },
            { "Growth Bell (Common)", "Otomo_PalExp_Increase_1" },
            { "Growth Bell (Uncommon)", "Otomo_PalExp_Increase_2" },
            { "Growth Bell (Rare)", "Otomo_PalExp_Increase_3" }
        }},
        { "Ammo", {
            { "Assault Rifle Ammo", "AssaultRifleBullet" },
            { "Arrow", "Arrow" },
            { "Coarse Ammo", "RoughBullet" },
            { "Decal Ink", "InkBullet" },
            { "Fire Arrow", "Arrow_Fire" },
            { "Handgun Ammo", "HandgunBullet" },
            { "Laser Ammo", "LaserBullet" },
            { "Machine Gun Ammo", "MachingunBullet" },
            { "Magnum Ammo", "MagnumBullet" },
            { "Poison Arrow", "Arrow_Poison" },
            { "Rocket Ammo", "ExplosiveBullet" },
            { "Rifle Ammo", "RifleBullet" },
            { "Shotgun Shells", "ShotgunBullet" },
            { "Charge Laser Bullet", "ChargeLaserRifleBullet" },
            { "Overheat Rifle Bullet", "OverheatRifleBullet" },
            { "Energy Shotgun Shell", "EnergyShotgunBullet" },
            { "Doping Syringe Round", "PalDopingShotBullet" },
            { "Tech Arrows", "SFArrow" },
            { "Reinforced Arrows", "ReinforcedArrow" }
        }},
        { "Armor", {
            { "Average Feed Bag", "AutoMealPouch_Tier2" },
            { "Cloth Outfit(Common)", "ClothArmor" },
            { "Cloth Outfit(Uncommon)", "ClothArmor_2" },
            { "Cloth Outfit(Rare)", "ClothArmor_3" },
            { "Cloth Outfit(Epic)", "ClothArmor_4" },
            { "Cloth Outfit(Legendary)", "ClothArmor_5" },
            { "Cold Resistant Metal Armor(Common)", "CopperArmorCold" },
            { "Cold Resistant Metal Armor(Uncommon)", "CopperArmorCold_2" },
            { "Cold Resistant Metal Armor(Rare)", "CopperArmorCold_3" },
            { "Cold Resistant Metal Armor(Epic)", "CopperArmorCold_4" },
            { "Cold Resistant Metal Armor(Legendary)", "CopperArmorCold_5" },
            { "Cold Resistant Pelt Armor(Common)", "FurArmorCold" },
            { "Cold Resistant Pelt Armor(Uncommon)", "FurArmorCold_2" },
            { "Cold Resistant Pelt Armor(Rare)", "FurArmorCold_3" },
            { "Cold Resistant Pelt Armor(Epic)", "FurArmorCold_4" },
            { "Cold Resistant Pelt Armor(Legendary)", "FurArmorCold_5" },
            { "Cold Resistant Refined Metal Armor(Common)", "IronArmorCold" },
            { "Cold Resistant Refined Metal Armor(Uncommon)", "IronArmorCold_2" },
            { "Cold Resistant Refined Metal Armor(Rare)", "IronArmorCold_3" },
            { "Cold Resistant Refined Metal Armor(Epic)", "IronArmorCold_4" },
            { "Cold Resistant Refined Metal Armor(Legendary)", "IronArmorCold_5" },
            { "Cold Resistant Pal Metal Armor(Common)", "StealArmorCold" },
            { "Cold Resistant Pal Metal Armor(Uncommon)", "StealArmorCold_2" },
            { "Cold Resistant Pal Metal Armor(Rare)", "StealArmorCold_3" },
            { "Cold Resistant Pal Metal Armor(Epic)", "StealArmorCold_4" },
            { "Cold Resistant Pal Metal Armor(Legendary)", "StealArmorCold_5" },
            { "Feathered Hair Band(Common)", "FurHelmet" },
            { "Feathered Hair Band(Uncommon)", "FurHelmet_2" },
            { "Feathered Hair Band(Rare)", "FurHelmet_3" },
            { "Feathered Hair Band(Epic)", "FurHelmet_4" },
            { "Feathered Hair Band(Legendary)", "FurHelmet_5" },
            { "Giant Feed Bag", "AutoMealPouch_Tier5" },
            { "Heat Resistant Metal Armor(Common)", "CopperArmorHeat" },
            { "Heat Resistant Metal Armor(Uncommon)", "CopperArmorHeat_2" },
            { "Heat Resistant Metal Armor(Rare)", "CopperArmorHeat_3" },
            { "Heat Resistant Metal Armor(Epic)", "CopperArmorHeat_4" },
            { "Heat Resistant Metal Armor(Legendary)", "CopperArmorHeat_5" },
            { "Heat Resistant Pelt Armor(Common)", "FurArmorHeat" },
            { "Heat Resistant Pelt Armor(Uncommon)", "FurArmorHeat_2" },
            { "Heat Resistant Pelt Armor(Rare)", "FurArmorHeat_3" },
            { "Heat Resistant Pelt Armor(Epic)", "FurArmorHeat_4" },
            { "Heat Resistant Pelt Armor(Legendary)", "FurArmorHeat_5" },
            { "Huge Feed Bag", "AutoMealPouch_Tier4" },
            { "Heat Resistant Refined Metal Armor(Common)", "IronArmorHeat" },
            { "Heat Resistant Refined Metal Armor(Uncommon)", "IronArmorHeat_2" },
            { "Heat Resistant Refined Metal Armor(Rare)", "IronArmorHeat_3" },
            { "Heat Resistant Refined Metal Armor(Epic)", "IronArmorHeat_4" },
            { "Heat Resistant Refined Metal Armor(Legendary)", "IronArmorHeat_5" },
            { "Heat Resistant Pal Metal Armor(Common)", "StealArmorHeat" },
            { "Heat Resistant Pal Metal Armor(Uncommon)", "StealArmorHeat_2" },
            { "Heat Resistant Pal Metal Armor(Rare)", "StealArmorHeat_3" },
            { "Heat Resistant Pal Metal Armor(Epic)", "StealArmorHeat_4" },
            { "Heat Resistant Pal Metal Armor(Legendary)", "StealArmorHeat_5" },
            { "Large Feed Bag", "AutoMealPouch_Tier3" },
            { "Metal Armor(Common)", "CopperArmor" },
            { "Metal Armor(Uncommon)", "CopperArmor_2" },
            { "Metal Armor(Rare)", "CopperArmor_3" },
            { "Metal Armor(Epic)", "CopperArmor_4" },
            { "Metal Armor(Legendary)", "CopperArmor_5" },
            { "Metal Helm(Common)", "CopperHelmet" },
            { "Metal Helm(Uncommon)", "CopperHelmet_2" },
            { "Metal Helm(Rare)", "CopperHelmet_3" },
            { "Metal Helm(Epic)", "CopperHelmet_4" },
            { "Metal Helm(Legendary)", "CopperHelmet_5" },
            { "Pelt Armor(Common)", "FurArmor" },
            { "Pelt Armor(Uncommon)", "FurArmor_2" },
            { "Pelt Armor(Rare)", "FurArmor_3" },
            { "Pelt Armor(Epic)", "FurArmor_4" },
            { "Pelt Armor(Legendary)", "FurArmor_5" },
            { "Pal Metal Armor(Common)", "StealArmor" },
            { "Pal Metal Armor(Uncommon)", "StealArmor_2" },
            { "Pal Metal Armor(Rare)", "StealArmor_3" },
            { "Pal Metal Armor(Epic)", "StealArmor_4" },
            { "Pal Metal Armor(Legendary)", "StealArmor_5" },
            { "Pal Metal Helm(Common)", "StealHelmet" },
            { "Pal Metal Helm(Uncommon)", "StealHelmet_2" },
            { "Pal Metal Helm(Rare)", "StealHelmet_3" },
            { "Pal Metal Helm(Epic)", "StealHelmet_4" },
            { "Pal Metal Helm(Legendary)", "StealHelmet_5" },
            { "Refined Metal Armor(Common)", "IronArmor" },
            { "Refined Metal Armor(Uncommon)", "IronArmor_2" },
            { "Refined Metal Armor(Rare)", "IronArmor_3" },
            { "Refined Metal Armor(Epic)", "IronArmor_4" },
            { "Refined Metal Armor(Legendary)", "IronArmor_5" },
            { "Refined Metal Helm(Common)", "IronHelmet" },
            { "Refined Metal Helm(Uncommon)", "IronHelmet_2" },
            { "Refined Metal Helm(Rare)", "IronHelmet_3" },
            { "Refined Metal Helm(Epic)", "IronHelmet_4" },
            { "Refined Metal Helm(Legendary)", "IronHelmet_5" },
            { "Small Feed Bag", "AutoMealPouch_Tier1" },
            { "Tundra Outfit(Common)", "ClothArmorCold" },
            { "Tundra Outfit(Uncommon)", "ClothArmorCold_2" },
            { "Tundra Outfit(Rare)", "ClothArmorCold_3" },
            { "Tundra Outfit(Epic)", "ClothArmorCold_4" },
            { "Tundra Outfit(Legendary)", "ClothArmorCold_5" },
            { "Tropical Outfit(Common)", "ClothArmorHeat" },
            { "Tropical Outfit(Uncommon)", "ClothArmorHeat_2" },
            { "Tropical Outfit(Rare)", "ClothArmorHeat_3" },
            { "Tropical Outfit(Epic)", "ClothArmorHeat_4" },
            { "Tropical Outfit(Legendary)", "ClothArmorHeat_5" },
            { "Hex Crystal Armor", "SFArmor(Common)" },
            { "Hex Crystal Armor", "SFArmor_2(Uncommon)" },
            { "Hex Crystal Armor", "SFArmor_3(Rare)" },
            { "Hex Crystal Armor", "SFArmor_4" },
            { "Hex Crystal Armor", "SFArmor_5" },
            { "Cold-Resistant Hex Crystal Armor(Common)", "SFArmorCold" },
            { "Cold-Resistant Hex Crystal Armor(Uncommon)", "SFArmorCold_2" },
            { "Cold-Resistant Hex Crystal Armor(Rare)", "SFArmorCold_3" },
            { "Cold-Resistant Hex Crystal Armor(Epic)", "SFArmorCold_4" },
            { "Cold-Resistant Hex Crystal Armor(Legendary)", "SFArmorCold_5" },
            { "Heat-Resistant Hex Crystal Armor(Common)", "SFArmorHeat" },
            { "Heat-Resistant Hex Crystal Armor(Uncommon)", "SFArmorHeat_2" },
            { "Heat-Resistant Hex Crystal Armor(Rare)", "SFArmorHeat_3" },
            { "Heat-Resistant Hex Crystal Armor(Epic)", "SFArmorHeat_4" },
            { "Heat-Resistant Hex Crystal Armor(Legendary)", "SFArmorHeat_5" },
            { "Lightweight Hex Crystal Armor(Common)", "SFArmorWeight" },
            { "Lightweight Hex Crystal Armor(Uncommon)", "SFArmorWeight_2" },
            { "Lightweight Hex Crystal Armor(Rare)", "SFArmorWeight_3" },
            { "Lightweight Hex Crystal Armor(Epic)", "SFArmorWeight_4" },
            { "Lightweight Hex Crystal Armor(Legendary)", "SFArmorWeight_5" },
            { "Holy Armor", "YakushimaArmor001" }
        }},
        { "Blueprints", {
            { "Blueprint Tropical Outfit(Uncommon)", "Blueprint_ClothArmorHeat_2" },
            { "Blueprint Tropical Outfit(Rare)", "Blueprint_ClothArmorHeat_3" },
            { "Blueprint Tropical Outfit(Epic)", "Blueprint_ClothArmorHeat_4" },
            { "Blueprint Tropical Outfit(Legendary)", "Blueprint_ClothArmorHeat_5" },
            { "Blueprint Tundra Outfit(Uncommon)", "Blueprint_ClothArmorCold_2" },
            { "Blueprint Tundra Outfit(Rare)", "Blueprint_ClothArmorCold_3" },
            { "Blueprint Tundra Outfit(Epic)", "Blueprint_ClothArmorCold_4" },
            { "Blueprint Tundra Outfit(Legendary)", "Blueprint_ClothArmorCold_5" },
            { "Blueprint Heat Resistant Pelt Armor(Uncommon)", "Blueprint_FurArmorHeat_2" },
            { "Blueprint Heat Resistant Pelt Armor(Rare)", "Blueprint_FurArmorHeat_3" },
            { "Blueprint Heat Resistant Pelt Armor(Epic)", "Blueprint_FurArmorHeat_4" },
            { "Blueprint Heat Resistant Pelt Armor(Legendary)", "Blueprint_FurArmorHeat_5" },
            { "Blueprint Cold Resistant Pelt Armor(Uncommon)", "Blueprint_FurArmorCold_2" },
            { "Blueprint Cold Resistant Pelt Armor(Rare)", "Blueprint_FurArmorCold_3" },
            { "Blueprint Cold Resistant Pelt Armor(Epic)", "Blueprint_FurArmorCold_4" },
            { "Blueprint Cold Resistant Pelt Armor(Legendary)", "Blueprint_FurArmorCold_5" },
            { "Blueprint Heat Resistant Metal Armor(Uncommon)", "Blueprint_CopperArmorHeat_2" },
            { "Blueprint Heat Resistant Metal Armor(Rare)", "Blueprint_CopperArmorHeat_3" },
            { "Blueprint Heat Resistant Metal Armor(Epic)", "Blueprint_CopperArmorHeat_4" },
            { "Blueprint Heat Resistant Metal Armor(Legendary)", "Blueprint_CopperArmorHeat_5" },
            { "Blueprint Cold Resistant Metal Armor(Uncommon)", "Blueprint_CopperArmorCold_2" },
            { "Blueprint Cold Resistant Metal Armor(Rare)", "Blueprint_CopperArmorCold_3" },
            { "Blueprint Cold Resistant Metal Armor(Epic)", "Blueprint_CopperArmorCold_4" },
            { "Blueprint Cold Resistant Metal Armor(Legendary)", "Blueprint_CopperArmorCold_5" },
            { "Blueprint Heat Resistant Refined Metal Armor(Uncommon)", "Blueprint_IronArmorHeat_2" },
            { "Blueprint Heat Resistant Refined Metal Armor(Rare)", "Blueprint_IronArmorHeat_3" },
            { "Blueprint Heat Resistant Refined Metal Armor(Epic)", "Blueprint_IronArmorHeat_4" },
            { "Blueprint Heat Resistant Refined Metal Armor(Legendary)", "Blueprint_IronArmorHeat_5" },
            { "Blueprint Cold Resistant Refined Metal Armor(Uncommon)", "Blueprint_IronArmorCold_2" },
            { "Blueprint Cold Resistant Refined Metal Armor(Rare)", "Blueprint_IronArmorCold_3" },
            { "Blueprint Cold Resistant Refined Metal Armor(Epic)", "Blueprint_IronArmorCold_4" },
            { "Blueprint Cold Resistant Refined Metal Armor(Legendary)", "Blueprint_IronArmorCold_5" },
            { "Blueprint Heat Resistant Pal Metal Armor(Uncommon)", "Blueprint_StealArmorHeat_2" },
            { "Blueprint Heat Resistant Pal Metal Armor(Rare)", "Blueprint_StealArmorHeat_3" },
            { "Blueprint Heat Resistant Pal Metal Armor(Epic)", "Blueprint_StealArmorHeat_4" },
            { "Blueprint Heat Resistant Pal Metal Armor(Legendary)", "Blueprint_StealArmorHeat_5" },
            { "Blueprint Cold Resistant Pal Metal Armor(Uncommon)", "Blueprint_StealArmorCold_2" },
            { "Blueprint Cold Resistant Pal Metal Armor(Rare)", "Blueprint_StealArmorCold_3" },
            { "Blueprint Cold Resistant Pal Metal Armor(Epic)", "Blueprint_StealArmorCold_4" },
            { "Blueprint Cold Resistant Pal Metal Armor(Legendary)", "Blueprint_StealArmorCold_5" },
            { "Blueprint Feathered Hair Band(Uncommon)", "Blueprint_FurHelmet_2" },
            { "Blueprint Feathered Hair Band(Rare)", "Blueprint_FurHelmet_3" },
            { "Blueprint Feathered Hair Band(Epic)", "Blueprint_FurHelmet_4" },
            { "Blueprint Feathered Hair Band(Legendary)", "Blueprint_FurHelmet_5" },
            { "Blueprint Metal Helm(Uncommon)", "Blueprint_CopperHelmet_2" },
            { "Blueprint Metal Helm(Rare)", "Blueprint_CopperHelmet_3" },
            { "Blueprint Metal Helm(Epic)", "Blueprint_CopperHelmet_4" },
            { "Blueprint Metal Helm(Legendary)", "Blueprint_CopperHelmet_5" },
            { "Blueprint Refined Metal Helm(Uncommon)", "Blueprint_IronHelmet_2" },
            { "Blueprint Refined Metal Helm(Rare)", "Blueprint_IronHelmet_3" },
            { "Blueprint Refined Metal Helm(Epic)", "Blueprint_IronHelmet_4" },
            { "Blueprint Refined Metal Helm(Legendary)", "Blueprint_IronHelmet_5" },
            { "Blueprint Pal Metal Helm(Uncommon)", "Blueprint_StealHelmet_2" },
            { "Blueprint Pal Metal Helm(Rare)", "Blueprint_StealHelmet_3" },
            { "Blueprint Pal Metal Helm(Epic)", "Blueprint_StealHelmet_4" },
            { "Blueprint Pal Metal Helm(Legendary)", "Blueprint_StealHelmet_5" },
            { "Blueprint Monarch's Crown(Common)", "Blueprint_Head001_1" },
            { "Blueprint Monarch's Crown(Uncommon)", "Blueprint_Head001_2" },
            { "Blueprint Monarch's Crown(Rare)", "Blueprint_Head001_3" },
            { "Blueprint Monarch's Crown(Epic)", "Blueprint_Head001_4" },
            { "Blueprint Monarch's Crown(Legendary)", "Blueprint_Head001_5" },
            { "Blueprint Golden Crown(Common)", "Blueprint_Head002_1" },
            { "Blueprint Golden Crown(Uncommon)", "Blueprint_Head002_2" },
            { "Blueprint Golden Crown(Rare)", "Blueprint_Head002_3" },
            { "Blueprint Golden Crown(Epic)", "Blueprint_Head002_4" },
            { "Blueprint Long-eared Headband(Common)", "Blueprint_Head003_1" },
            { "Blueprint Long-eared Headband(Uncommon)", "Blueprint_Head003_2" },
            { "Blueprint Long-eared Headband(Rare)", "Blueprint_Head003_3" },
            { "Blueprint Long-eared Headband(Epic)", "Blueprint_Head003_4" },
            { "Blueprint Long-eared Headband(Legendary)", "Blueprint_Head003_5" },
            { "Blueprint Witch Hat(Common)", "Blueprint_Head004_1" },
            { "Blueprint Witch Hat(Uncommon)", "Blueprint_Head004_2" },
            { "Blueprint Witch Hat(Rare)", "Blueprint_Head004_3" },
            { "Blueprint Witch Hat(Epic)", "Blueprint_Head004_4" },
            { "Blueprint Witch Hat(Legendary)", "Blueprint_Head004_5" },
            { "Blueprint Soft Hat(Common)", "Blueprint_Head005_1" },
            { "Blueprint Soft Hat(Uncommon)", "Blueprint_Head005_2" },
            { "Blueprint Soft Hat(Rare)", "Blueprint_Head005_3" },
            { "Blueprint Soft Hat(Epic)", "Blueprint_Head005_4" },
            { "Blueprint Soft Hat(Legendary)", "Blueprint_Head005_5" },
            { "Blueprint Helmet(Common)", "Blueprint_Head006_1" },
            { "Blueprint Helmet(Uncommon)", "Blueprint_Head006_2" },
            { "Blueprint Helmet(Rare)", "Blueprint_Head006_3" },
            { "Blueprint Helmet(Epic)", "Blueprint_Head006_4" },
            { "Blueprint Helmet(Legendary)", "Blueprint_Head006_5" },
            { "Blueprint Silt Hat(Common)", "Blueprint_Head007_1" },
            { "Blueprint Silt Hat(Uncommon)", "Blueprint_Head007_2" },
            { "Blueprint Silt Hat(Rare)", "Blueprint_Head007_3" },
            { "Blueprint Silt Hat(Epic)", "Blueprint_Head007_4" },
            { "Blueprint Silt Hat(Legendary)", "Blueprint_Head007_5" },
            { "Blueprint Tricorne(Common)", "Blueprint_Head008_1" },
            { "Blueprint Tricorne(Uncommon)", "Blueprint_Head008_2" },
            { "Blueprint Tricorne(Rare)", "Blueprint_Head008_3" },
            { "Blueprint Tricorne(Epic)", "Blueprint_Head008_4" },
            { "Blueprint Tricorne(Legendary)", "Blueprint_Head008_5" },
            { "Blueprint Explorer Cap(Common)", "Blueprint_Head009_1" },
            { "Blueprint Explorer Cap(Uncommon)", "Blueprint_Head009_2" },
            { "Blueprint Explorer Cap(Rare)", "Blueprint_Head009_3" },
            { "Blueprint Explorer Cap(Epic)", "Blueprint_Head009_4" },
            { "Blueprint Explorer Cap(Legendary)", "Blueprint_Head009_5" },
            { "Blueprint Graduation Cap(Common)", "Blueprint_Head010_1" },
            { "Blueprint Graduation Cap(Uncommon)", "Blueprint_Head010_2" },
            { "Blueprint Graduation Cap(Rare)", "Blueprint_Head010_3" },
            { "Blueprint Graduation Cap(Epic)", "Blueprint_Head010_4" },
            { "Blueprint Graduation Cap(Legendary)", "Blueprint_Head010_5" },
            { "Blueprint Farming Hat(Common)", "Blueprint_Head011_1" },
            { "Blueprint Farming Hat(Uncommon)", "Blueprint_Head011_2" },
            { "Blueprint Farming Hat(Rare)", "Blueprint_Head011_3" },
            { "Blueprint Farming Hat(Epic)", "Blueprint_Head011_4" },
            { "Blueprint Farming Hat(Legendary)", "Blueprint_Head011_5" },
            { "Blueprint Bowler Hat(Common)", "Blueprint_Head012_1" },
            { "Blueprint Bowler Hat(Uncommon)", "Blueprint_Head012_2" },
            { "Blueprint Bowler Hat(Rare)", "Blueprint_Head012_3" },
            { "Blueprint Bowler Hat(Epic)", "Blueprint_Head012_4" },
            { "Blueprint Bowler Hat(Legendary)", "Blueprint_Head012_5" },
            { "Blueprint Tocotoco Cap(Common)", "Blueprint_Head013_1" },
            { "Blueprint Tocotoco Cap(Uncommon)", "Blueprint_Head013_2" },
            { "Blueprint Tocotoco Cap(Rare)", "Blueprint_Head013_3" },
            { "Blueprint Tocotoco Cap(Epic)", "Blueprint_Head013_4" },
            { "Blueprint Tocotoco Cap(Legendary)", "Blueprint_Head013_5" },
            { "Blueprint Grinning Tocotoco Cap(Common)", "Blueprint_Head014_1" },
            { "Blueprint Grinning Tocotoco Cap(Uncommon)", "Blueprint_Head014_2" },
            { "Blueprint Grinning Tocotoco Cap(Rare)", "Blueprint_Head014_3" },
            { "Blueprint Grinning Tocotoco Cap(Epic)", "Blueprint_Head014_4" },
            { "Blueprint Grinning Tocotoco Cap(Legendary)", "Blueprint_Head014_5" },
            { "Blueprint Gusmoss Cap(Common)", "Blueprint_Head015_1" },
            { "Blueprint Gusmoss Cap(Uncommon)", "Blueprint_Head015_2" },
            { "Blueprint Gusmoss Cap(Rare)", "Blueprint_Head015_3" },
            { "Blueprint Gusmoss Cap(Epic)", "Blueprint_Head015_4" },
            { "Blueprint Gusmoss Cap(Legendary)", "Blueprint_Head015_5" },
            { "Blueprint Penking Cap(Common)", "Blueprint_Head016_1" },
            { "Blueprint Penking Cap(Uncommon)", "Blueprint_Head016_2" },
            { "Blueprint Penking Cap(Rare)", "Blueprint_Head016_3" },
            { "Blueprint Penking Cap(Epic)", "Blueprint_Head016_4" },
            { "Blueprint Penking Cap(Legendary)", "Blueprint_Head016_5" },
            { "Blueprint Katress Cap(Common)", "Blueprint_Head017_1" },
            { "Blueprint Katress Cap(Uncommon)", "Blueprint_Head017_2" },
            { "Blueprint Katress Cap(Rare)", "Blueprint_Head017_3" },
            { "Blueprint Katress Cap(Epic)", "Blueprint_Head017_4" },
            { "Blueprint Katress Cap(Legendary)", "Blueprint_Head017_5" },
            { "Blueprint Old Bow(Uncommon)", "Blueprint_WeakerBow_2" },
            { "Blueprint Old Bow(Rare)", "Blueprint_WeakerBow_3" },
            { "Blueprint Old Bow(Epic)", "Blueprint_WeakerBow_4" },
            { "Blueprint Old Bow(Legendary)", "Blueprint_WeakerBow_5" },
            { "Blueprint Crossbow(Uncommon)", "Blueprint_BowGun_2" },
            { "Blueprint Crossbow(Rare)", "Blueprint_BowGun_3" },
            { "Blueprint Crossbow(Epic)", "Blueprint_BowGun_4" },
            { "Blueprint Crossbow(Legendary)", "Blueprint_BowGun_5" },
            { "Blueprint Assault Rifle(Uncommon)", "Blueprint_AssaultRifle_Default2" },
            { "Blueprint Assault Rifle(Rare)", "Blueprint_AssaultRifle_Default3" },
            { "Blueprint Assault Rifle(Epic)", "Blueprint_AssaultRifle_Default4" },
            { "Blueprint Assault Rifle(Legendary)", "Blueprint_AssaultRifle_Default5" },
            { "Blueprint Pump Action Shotgun(Uncommon)", "Blueprint_PumpActionShotgun_2" },
            { "Blueprint Pump Action Shotgun(Rare)", "Blueprint_PumpActionShotgun_3" },
            { "Blueprint Pump Action Shotgun(Epic)", "Blueprint_PumpActionShotgun_4" },
            { "Blueprint Pump Action Shotgun(Legendary)", "Blueprint_PumpActionShotgun_5" },
            { "Blueprint Handgun(Uncommon)", "Blueprint_HandGun_Default_2" },
            { "Blueprint Handgun(Rare)", "Blueprint_HandGun_Default_3" },
            { "Blueprint Handgun(Epic)", "Blueprint_HandGun_Default_4" },
            { "Blueprint Handgun(Legendary)", "Blueprint_HandGun_Default_5" },
            { "Blueprint Rocket Launcher(Uncommon)", "Blueprint_Launcher_Default_2" },
            { "Blueprint Rocket Launcher(Rare)", "Blueprint_Launcher_Default_3" },
            { "Blueprint Rocket Launcher(Epic)", "Blueprint_Launcher_Default_4" },
            { "Blueprint Rocket Launcher(Legendary)", "Blueprint_Launcher_Default_5" },
            { "Semi-Auto Shotgun(Uncommon)", "Blueprint_SemiAutoShotgun_2" },
            { "Semi-Auto Shotgun(Rare)", "Blueprint_SemiAutoShotgun_3" },
            { "Semi-Auto Shotgun(Epic)", "Blueprint_SemiAutoShotgun_4" },
            { "Semi-Auto Shotgun(Legendary)", "Blueprint_SemiAutoShotgun_5" },
            { "Semi-Auto Rifle(Rare)", "Blueprint_SemiAutoRifle_3" },
            { "Semi-Auto Rifle(Epic)", "Blueprint_SemiAutoRifle_4" },
            { "Semi-Auto Rifle(Legendary)", "Blueprint_SemiAutoRifle_5" },
            { "Hex Crystal Armor(Uncommon)", "Blueprint_SFArmor_2" },
            { "Hex Crystal Armor(Rare)", "Blueprint_SFArmor_3" },
            { "Hex Crystal Armor(Epic)", "Blueprint_SFArmor_4" },
            { "Hex Crystal Armor(Legendary)", "Blueprint_SFArmor_5" },
            { "Hex Crystal Helmet(Uncommon)", "Blueprint_SFHelmet_2" },
            { "Hex Crystal Helmet(Rare)", "Blueprint_SFHelmet_3" },
            { "Hex Crystal Helmet(Epic)", "Blueprint_SFHelmet_4" },
            { "Hex Crystal Helmet(Legendary)", "Blueprint_SFHelmet_5" },
            { "Cold-Resistant Hex Crystal Armor(Uncommon)", "Blueprint_SFArmorCold_2" },
            { "Cold-Resistant Hex Crystal Armor(Rare)", "Blueprint_SFArmorCold_3" },
            { "Cold-Resistant Hex Crystal Armor(Epic)", "Blueprint_SFArmorCold_4" },
            { "Cold-Resistant Hex Crystal Armor(Legendary)", "Blueprint_SFArmorCold_5" }
        }},
        { "Crafting Materials", {
            { "Ancient Civilization Parts", "PalCrystal_Ex" },
            { "Bone", "Bone" },
            { "Beautiful Flowers", "Poppy" },
            { "Crude Oil", "CrudeOil" },
            { "Claws", "Claws" },
            { "Cloth", "Cloth" },
            { "Coal", "Coal" },
            { "Cement", "Cement" },
            { "Charcoal", "Charcoal" },
            { "Carbon Fiber", "CarbonFiber" },
            { "Circuit Board", "MachineParts2" },
            { "Electric Organ", "ElectricOrgan" },
            { "Flour", "Flour" },
            { "Fiber", "Fiber" },
            { "Flame Organ", "FireOrgan" },
            { "Gunpowder", "GunPowder2" },
            { "Gumoss Leaf", "PalItem_PlantSlime" },
            { "High Quality Cloth", "Cloth2" },
            { "High Quality Pal Oil", "PalOil" },
            { "Horn", "Horn" },
            { "Ingot", "CopperIngot" },
            { "Ice Organ", "IceOrgan" },
            { "Katress Hair", "PalItem_CatMage" },
            { "Leather", "Leather" },
            { "Nails", "MachineParts" },
            { "Ore", "CopperOre" },
            { "Pal Fluids", "PalFluid" },
            { "Polymer", "Polymer" },
            { "Paldium Clump", "Pal_crystal_L" },
            { "Paldium Fragment", "Pal_crystal_S" },
            { "Pal Metal Ingot", "StealIngot" },
            { "Pure Quartz", "Quartz" },
            { "Punking Plume", "PalItem_CaptainPenguin" },
            { "Refined Ingot", "IronIngot" },
            { "Stone", "Stone" },
            { "Sulfur", "Sulfur" },
            { "Tocotoco Feather", "PalItem_ColorfulBird" },
            { "Venom Gland", "Venom" },
            { "Wood", "Wood" },
            { "Wool", "Wool" }
        }},
        { "Eggs", {
            { "Dark Egg", "PalEgg_Dark_01" },
            { "Dark Egg(2)", "PalEgg_Dark_02" },
            { "Large Dark Egg", "PalEgg_Dark_03" },
            { "Large Dark Egg(2)", "PalEgg_Dark_04" },
            { "Huge Dark Egg", "PalEgg_Dark_05" },
            { "Dragon Egg", "PalEgg_Dragon_01" },
            { "Dragon Egg(2)", "PalEgg_Dragon_02" },
            { "Large Dragon Egg", "PalEgg_Dragon_03" },
            { "Large Dragon Egg(2)", "PalEgg_Dragon_04" },
            { "Huge Dragon Egg", "PalEgg_Dragon_05" },
            { "Rocky Egg", "PalEgg_Earth_01" },
            { "Rough Egg(2)", "PalEgg_Earth_02" },
            { "Large Rocky Egg", "PalEgg_Earth_03" },
            { "Large Rocky Egg(2)", "PalEgg_Earth_04" },
            { "Huge Rocky Egg", "PalEgg_Earth_05" },
            { "Electric Egg", "PalEgg_Electricity_01" },
            { "Electric Egg(2)", "PalEgg_Electricity_02" },
            { "Large Electric Egg", "PalEgg_Electricity_03" },
            { "Large Electric Egg(2)", "PalEgg_Electricity_04" },
            { "Huge Electric Egg", "PalEgg_Electricity_05" },
            { "Scorching Egg", "PalEgg_Fire_01" },
            { "Scorching Egg(2)", "PalEgg_Fire_02" },
            { "Large Scorching Egg", "PalEgg_Fire_03" },
            { "Large Scorching Egg(2)", "PalEgg_Fire_04" },
            { "Huge Scorching Egg", "PalEgg_Fire_05" },
            { "Frozen Egg", "PalEgg_Ice_01" },
            { "Frozen Egg(2)", "PalEgg_Ice_02" },
            { "Large Frozen Egg", "PalEgg_Ice_03" },
            { "Large Frozen Egg(2)", "PalEgg_Ice_04" },
            { "Huge Frozen Egg", "PalEgg_Ice_05" },
            { "Verdant Egg", "PalEgg_Leaf_01" },
            { "Verdant Egg(2)", "PalEgg_Leaf_02" },
            { "Large Verdant Egg", "PalEgg_Leaf_03" },
            { "Large Verdant Egg(2)", "PalEgg_Leaf_04" },
            { "Huge Verdant Egg", "PalEgg_Leaf_05" },
            { "Common Egg", "PalEgg_Normal_01" },
            { "Common Egg(2)", "PalEgg_Normal_02" },
            { "Large Common Egg", "PalEgg_Normal_03" },
            { "Large Common Egg(2)", "PalEgg_Normal_04" },
            { "Huge Common Egg", "PalEgg_Normal_05" },
            { "Damp Egg", "PalEgg_Water_01" },
            { "Damp Egg(2)", "PalEgg_Water_02" },
            { "Large Damp Egg", "PalEgg_Water_03" },
            { "Large Damp Egg(2)", "PalEgg_Water_04" },
            { "Huge Damp Egg", "PalEgg_Water_05" }
        }},
        { "Food", {
            { "Burrito", "BLT" },
            { "Broiled Dumund", "BakedMeat_LazyCatfish" },
            { "Broncherry Rib Roast", "BakedMeat_SakuraSaurus" },
            { "Baked Mushrooms", "BakedMushroom" },
            { "Baked Berries", "Baked_Berries" },
            { "Bolognese Sauce", "MeatSauce" },
            { "Broncherry Meat", "Meat_SakuraSaurus" },
            { "Bread", "Pan" },
            { "Cake", "Cake" },
            { "Cheeseburger", "CheeseBurger" },
            { "Chikipi Sauté", "ChickenSaute" },
            { "Carbonara", "Carbonara" },
            { "Caprity Meat", "Meat_BerryGoat" },
            { "Chikipi Poultry", "Meat_ChickenPal" },
            { "Cotton Candy", "Sweet" },
            { "Dumund Chowder", "Chowder" },
            { "Egg", "Egg" },
            { "Eikthyrdeer Loco Moco", "DeerLocoMoco" },
            { "Eikthyrdeer Stew", "DeerStew" },
            { "Eikthyrdeer Venison", "Meat_Deer" },
            { "Fried Chikipi", "FriedChicken" },
            { "Fried Eggs", "FriedEggs" },
            { "Fried Kepsea", "FriedKelpie" },
            { "Grilled Chikipi", "BakedMeat_ChickenPal" },
            { "Grilled Galeclaw", "BakedMeat_Eagle" },
            { "Grilled Kelpsea", "BakedMeat_Kelpie" },
            { "Galeclaw Poultry", "Meat_Eagle" },
            { "Grilled Meat", "GrilledMeat" },
            { "Grilled Lamball", "GenghisKhan" },
            { "Herb Roasted Caprity", "BakedMeat_BerryGoat" },
            { "Honey", "Honey" },
            { "Hot Dog", "HotDog" },
            { "Hot Milk", "HotMilk" },
            { "Herb Roasted Lamball", "GrilledSheepHerbs" },
            { "Hamburger", "Hamburger" },
            { "Jam-filled Bun", "JamBun" },
            { "Lamball Kebab", "BakedMeat_SheepBall" },
            { "Lamball Mutton", "Meat_SheepBall" },
            { "Lettuce", "Lettuce" },
            { "Moazzarina Steak", "BakedMeat_CowPal" },
            { "Mammorest Steak", "BakedMeat_GrassMammoth" },
            { "Mozzarina Cheeseburger", "CheeseBurger_2" },
            { "Mozzarina Meat", "Meat_CowPal" },
            { "Mammorest Meat", "Meat_GrassMammoth" },
            { "Mozzarina Hamburger", "Hamburger_2" },
            { "Milk", "Milk" },
            { "Marinated Mushrooms", "MarinatedMushrooms" },
            { "Mushroom Soup", "MushroomSoup" },
            { "Mushroom", "Mushroom" },
            { "Omelet", "Omelet" },
            { "Pancake", "Pancake" },
            { "Pizza", "Pizza" },
            { "Rushoar Bacon 'n' Eggs", "BaconEggs" },
            { "Roast Rushoar", "BakedMeat_Boar" },
            { "Roast Eikthyrdeer", "BakedMeat_Deer" },
            { "Roast Reindrix", "BakedMeat_IceDeer" },
            { "Roshoar Pork", "Meat_Boar" },
            { "Reindrix Venison", "Meat_IceDeer" },
            { "Raw Kelpsea", "Meat_Kelpie" },
            { "Raw Dumund", "Meat_LazyCatfish" },
            { "Raw Meat", "Meat" },
            { "Rushoar Hot Dog", "HotDog_2" },
            { "Reindrix Stew", "StewedIceDeer" },
            { "Red Wild Berries", "Berries" },
            { "Stewed Galeclaw", "Eaglestew" },
            { "Stir-fried Veggies", "FriedVegetables" },
            { "Salad", "Salad" },
            { "Stewed Mushrooms", "MushroomStew" },
            { "Tomato", "Tomato" },
            { "Wheat", "Wheat" },
            { "Carrot", "Carrot" },
            { "Onion", "Onion" },
            { "Potato", "Potato" },
            { "Savannah Mammoth Curry", "Curry" },
            { "Gratin", "Gratin" },
            { "Wild Boar Dumplings", "Gyoza" },
            { "Stewed Meat & Potatoes", "MeatAndPotatoes" },
            { "Minestrone Soup", "Minestrone" },
            { "Potato Chips", "PotatoChips" },
            { "Mushroom Quiche", "Quiche" },
            { "Stir-fried Vegetables", "StirFriedVegetables" }
        }},
        { "Hats", {
            { "Bowler Hat(Common)", "Head012" },
            { "Bowler Hat(Uncommon)", "Head012_2" },
            { "Bowler Hat(Rare)", "Head012_3" },
            { "Bowler Hat(Epic)", "Head012_4" },
            { "Bowler Hat(Legendary)", "Head012_5" },
            { "Explorer Cap(Common)", "Head009" },
            { "Explorer Cap(Uncommon)", "Head009_2" },
            { "Explorer Cap(Rare)", "Head009_3" },
            { "Explorer Cap(Epic)", "Head009_4" },
            { "Explorer Cap(Legendary)", "Head009_5" },
            { "Farming Hat(Common)", "Head011" },
            { "Farming Hat(Uncommon)", "Head011_2" },
            { "Farming Hat(Rare)", "Head011_3" },
            { "Farming Hat(Epic)", "Head011_4" },
            { "Farming Hat(Legendary)", "Head011_5" },
            { "Golden Crown(Common)", "Head002" },
            { "Golden Crown(Uncommon)", "Head002_2" },
            { "Golden Crown(Rare)", "Head002_3" },
            { "Golden Crown(Epic)", "Head002_4" },
            { "Golden Crown(Legendary)", "Head002_5" },
            { "Graduation Cap(Common)", "Head010" },
            { "Graduation Cap(Uncommon)", "Head010_2" },
            { "Graduation Cap(Rare)", "Head010_3" },
            { "Graduation Cap(Epic)", "Head010_4" },
            { "Graduation Cap(Legendary)", "Head010_5" },
            { "Grinning Tocotoco Cap(Common)", "Head014" },
            { "Grinning Tocotoco Cap(Uncommon)", "Head014_2" },
            { "Grinning Tocotoco Cap(Rare)", "Head014_3" },
            { "Grinning Tocotoco Cap(Epic)", "Head014_4" },
            { "Grinning Tocotoco Cap(Legendary)", "Head014_5" },
            { "Gusmoss Cap(Common)", "Head015" },
            { "Gusmoss Cap(Uncommon)", "Head015_2" },
            { "Gusmoss Cap(Rare)", "Head015_3" },
            { "Gusmoss Cap(Epic)", "Head015_4" },
            { "Gusmoss Cap(Legendary)", "Head015_5" },
            { "Helmet(Common)", "Head006" },
            { "Helmet(Uncommon)", "Head006_2" },
            { "Helmet(Rare)", "Head006_3" },
            { "Helmet(Epic)", "Head006_4" },
            { "Helmet(Legendary)", "Head006_5" },
            { "Katress Cap(Common)", "Head017" },
            { "Katress Cap(Uncommon)", "Head017_2" },
            { "Katress Cap(Rare)", "Head017_3" },
            { "Katress Cap(Epic)", "Head017_4" },
            { "Katress Cap(Legendary)", "Head017_5" },
            { "Long-eared Headband(Common)", "Head003" },
            { "Long-eared Headband(Uncommon)", "Head003_2" },
            { "Long-eared Headband(Rare)", "Head003_3" },
            { "Long-eared Headband(Epic)", "Head003_4" },
            { "Long-eared Headband(Legendary)", "Head003_5" },
            { "Monarch's Crown(Common)", "Head001" },
            { "Monarch's Crown(Uncommon)", "Head001_2" },
            { "Monarch's Crown(Rare)", "Head001_3" },
            { "Monarch's Crown(Epic)", "Head001_4" },
            { "Monarch's Crown(Legendary)", "Head001_5" },
            { "Penking Cap(Common)", "Head016" },
            { "Penking Cap(Uncommon)", "Head016_2" },
            { "Penking Cap(Rare)", "Head016_3" },
            { "Penking Cap(Epic)", "Head016_4" },
            { "Penking Cap(Legendary)", "Head016_5" },
            { "Soft Hat(Common)", "Head005" },
            { "Soft Hat(Uncommon)", "Head005_2" },
            { "Soft Hat(Rare)", "Head005_3" },
            { "Soft Hat(Epic)", "Head005_4" },
            { "Soft Hat(Legendary)", "Head005_5" },
            { "Silk Hat(Common)", "Head007" },
            { "Silk Hat(Uncommon)", "Head007_2" },
            { "Silk Hat(Rare)", "Head007_3" },
            { "Silk Hat(Epic)", "Head007_4" },
            { "Silk Hat(Legendary)", "Head007_5" },
            { "Tricorne(Common)", "Head008" },
            { "Tricorne(Uncommon)", "Head008_2" },
            { "Tricorne(Rare)", "Head008_3" },
            { "Tricorne(Epic)", "Head008_4" },
            { "Tricorne(Legendary)", "Head008_5" },
            { "Tocotoco Cap(Common)", "Head013" },
            { "Tocotoco Cap(Uncommon)", "Head013_2" },
            { "Tocotoco Cap(Rare)", "Head013_3" },
            { "Tocotoco Cap(Epic)", "Head013_4" },
            { "Tocotoco Cap(Legendary)", "Head013_5" },
            { "Witch Hat(Common)", "Head004" },
            { "Witch Hat(Uncommon)", "Head004_2" },
            { "Witch Hat(Rare)", "Head004_3" },
            { "Witch Hat(Epic)", "Head004_4" },
            { "Witch Hat(Legendary)", "Head004_5" },
            { "Bjorn's Hat", "GYM_Head_Viking" },
            { "JenoDoran Headgear", "HeadEquip044" },
            { "Hex Crystal Helmet (Common)", "SFHelmet" },
            { "Hex Crystal Helmet (Uncommon)", "SFHelmet_2" },
            { "Hex Crystal Helmet (Rare)", "SFHelmet_3" },
            { "Hex Crystal Helmet (Epic)", "SFHelmet_4" },
            { "Hex Crystal Helmet (Legendary)", "SFHelmet_5" },
            { "Holy Mask (Common)", "YakushimaHeadEquip001" },
            { "Holy Mask (Uncommon)", "YakushimaHeadEquip001_2" },
            { "Holy Mask (Rare)", "YakushimaHeadEquip001_3" },
            { "Holy Mask (Epic)", "YakushimaHeadEquip001_4" },
            { "Holy Mask (Legendary)", "YakushimaHeadEquip001_5" },
            { "Holy Circlet (Common)", "YakushimaHeadEquip002" },
            { "Holy Circlet (Uncommon)", "YakushimaHeadEquip002_2" },
            { "Holy Circlet (Rare)", "YakushimaHeadEquip002_3" },
            { "Holy Circlet (Epic)", "YakushimaHeadEquip002_4" },
            { "Holy Circlet (Legendary)", "YakushimaHeadEquip002_5" },
            { "Holy Helmet (Rare)", "YakushimaHeadEquip003" },
            { "Holy Hood (Epic)", "YakushimaHeadEquip004" },
            { "Holy Hood (Legendary)", "YakushimaHeadEquip004_4" },
            { "Holy Hood (Mythic)", "YakushimaHeadEquip004_5" },
            { "Moon Lord Mask (Legendary)", "YakushimaHeadEquip005" },
            { "Eye of Cthulhu Mask (Epic)", "YakushimaHeadEquip006" }
        }},
        { "Medicine", {
            { "High Grade Medical Supplies", "LuxuryMedicines" },
            { "Low Quality Medical Supplies", "Herbs" },
            { "Medical Supplies", "Medicines" },
            { "Mind Control Meds", "MindControlDrug" },
            { "Memory Wiping Medicine", "StatusPointResetSan" },
            { "Strange Juice", "Narcotic" },
            { "Suspicious Juice", "Opium" },
            { "Revival Medicine", "PalRevive" },
            { "Supreme Healing Potion", "Potion_Extreme" }
        }},
        { "Other", {
            { "Dung", "Unko_S" },
            { "Future Technical Manual", "TechnologyBook_G3" },
            { "High Grade Technical Manual", "TechnologyBook_G1" },
            { "Huge Dung Pile", "Unko_L" },
            { "Innovative Technical Manual", "TechnologyBook_G2" },
            { "Large Pal Soul", "PalUpgradeStone3" },
            { "Lifmunk Effigy", "Relic" },
            { "Medium Pal Soul", "PalUpgradeStone2" },
            { "Precious Dragon Stone", "PalItem_ToSell_01" },
            { "Precious Plume", "PalItem_ToSell_02" },
            { "Precious Entrails", "PalItem_ToSell_03" },
            { "Precious Claw", "PalItem_ToSell_04" },
            { "Precious Pelt", "PalItem_ToSell_05" },
            { "Small Pal Soul", "PalUpgradeStone" },
            { "Farmer's Special Dish", "QuestItem_Farmer_1" },
            { "Zoe’s Memory Cloth", "QuestItem_Zoe_1" },
            { "Breeder’s Beloved Pal", "QuestItem_Breeder_1" },
            { "Battle Ticket", "BattleTicket" },
            { "Discarded Genetic Sample", "MeaninglessItem_ButcheringImportPal" },
            { "Celestial Sigil", "PalSummon_YakushimaBoss002" }
        }},
        { "Pal Spheres", {
            { "Pal Sphere [Power 7]", "PalSphere" },
            { "Mega Sphere [Power 14]", "PalSphere_Mega" },
            { "Giga Sphere [Power 20]", "PalSphere_Giga" },
            { "Hyper Sphere [Power 26]", "PalSphere_Tera" },
            { "Ultra Sphere [Power 32]", "PalSphere_Master" },
            { "Legendary Sphere [Power 37]", "PalSphere_Legend" },
            { "Ultimate Sphere [Power 43]", "PalSphere_Ultimate" },
            { "Exotic Sphere [Power 48]", "PalSphere_Exotic" },
            { "Dev Sphere [Palguard Detected]", "PalSphere_Debug" },
            { "Radar Sphere", "PalSphere_Robbery" }
        }},
        { "Seeds", {
            { "Berry Seeds", "BerrySeeds" },
            { "Lettuce Seeds", "LettuceSeeds" },
            { "Tomato Seeds", "TomatoSeeds" },
            { "Wheat Seeds", "WheatSeeds" },
            { "Carrot Seeds", "CarrotSeeds" },
            { "Onion Seeds", "OnionSeeds" },
            { "Potato Seed Potatoes", "PotatoSeeds" }
        }},
        { "Tools", {
            { "Common Shield", "Shield_01" },
            { "Copper Key", "TreasureBoxKey01" },
            { "Super Glider", "Glider_Super" },
            { "Giga Shield", "Shield_03" },
            { "Golden Key", "TreasureBoxKey03" },
            { "Legendary Glider", "Glider_Legendary" },
            { "Hip Lantern", "Lantern" },
            { "High-Powered Waist Lantern", "Lantern_High" },
            { "HyperShield", "Shield_04" },
            { "Hand-held Torch", "Torch" },
            { "Metal Ax", "Axe_Tier_01" },
            { "Metal Pickaxe", "Pickaxe_Tier_01" },
            { "Mega Glider", "Glider_Good" },
            { "Mega Shield", "Shield_02" },
            { "Meat Cleaver", "MeatCutterKnife" },
            { "Normal Glider", "Glider_Old" },
            { "Refined Metal Ax", "Axe_Tier_02" },
            { "Refined Metal Pickaxe", "Pickaxe_Tier_02" },
            { "Repair Kit", "RepairKit" },
            { "Stone Ax", "Axe_Tier_00" },
            { "Stone Pickaxe", "Pickaxe_Tier_00" },
            { "Silver Key", "TreasureBoxKey02" },
            { "Pal Metal Axe", "Axe_Steal" },
            { "Pal Metal Pickaxe", "Pickaxe_Steal" },
            { "Metal Detector", "MetalDetector" },
            { "Grappling Gun", "GrapplingGun" },
            { "Mega Grappling Gun", "GrapplingGun2" },
            { "Giga Grappling Gun", "GrapplingGun3" },
            { "Hyper Grappling Gun", "GrapplingGun4" },
            { "Super Grappling Gun", "GrapplingGun5" }
        }},
        { "Weapons", {
            { "Assault Rifle(Common)", "AssaultRifle_Default1" },
            { "Assault Rifle(Uncommon)", "AssaultRifle_Default2" },
            { "Assault Rifle(Rare)", "AssaultRifle_Default3" },
            { "Assault Rifle(Epic)", "AssaultRifle_Default4" },
            { "Assault Rifle(Legendary)", "AssaultRifle_Default5" },
            { "Bat", "Bat2" },
            { "Beegarde's Spear", "Spear_SoldierBee" },
            { "Crossbow(Common)", "BowGun" },
            { "Crossbow(Uncommon)", "BowGun_2" },
            { "Crossbow(Rare)", "BowGun_3" },
            { "Crossbow(Epic)", "BowGun_4" },
            { "Crossbow(Legendary)", "BowGun_5" },
            { "Decal Gun 1", "DecalGun_1" },
            { "Decal Gun 2", "DecalGun_2" },
            { "Decal Gun 3", "DecalGun_3" },
            { "Decal Gun 4", "DecalGun_4" },
            { "Decal Gun 5", "DecalGun_5" },
            { "Double-barreled Shotgun", "DoubleBarrelShotgun" },
            { "Elizabee's Staff", "Spear_QueenBee" },
            { "Fire Arrow Crossbow", "BowGun_Fire" },
            { "Five Shot Bow", "Bow_Fifth" },
            { "Fire Bow", "Bow_Fire" },
            { "Frag Grenade", "FragGrenade" },
            { "Homing Sphere Launcher", "HomingSphereLauncher" },
            { "Incendiary Grenade", "FragGrenade_Fire" },
            { "Ice Grenade", "FragGrenade_Ice" },
            { "Inferior Handgun", "MakeshiftHandgun" },
            { "Laser Rifle", "LaserRifle" },
            { "Lily's Spear", "Spear_ForestBoss" },
            { "Musket", "Musket" },
            { "Metal Spear", "Spear_2" },
            { "Old Bow(Common)", "WeakerBow" },
            { "Old Bow(Uncommon)", "WeakerBow_2" },
            { "Old Bow(Rare)", "WeakerBow_3" },
            { "Old Bow(Epic)", "WeakerBow_4" },
            { "Old Bow(Legendary)", "WeakerBow_5" },
            { "Poison Arrow Crossbow", "BowGun_Poison" },
            { "Poison Bow", "Bow_Poison" },
            { "Pistol(Common)", "HandGun_Default" },
            { "Pistol(Uncommon)", "HandGun_Default_2" },
            { "Pistol(Rare)", "HandGun_Default_3" },
            { "Pistol(Epic)", "HandGun_Default_4" },
            { "Pistol(Legendary)", "HandGun_Default_5" },
            { "Pump Action Shotgun(Common)", "PumpActionShotgun" },
            { "Pump Action Shotgun(Uncommon)", "PumpActionShotgun_2" },
            { "Pump Action Shotgun(Rare)", "PumpActionShotgun_3" },
            { "Pump Action Shotgun(Epic)", "PumpActionShotgun_4" },
            { "Pump Action Shotgun(Legendary)", "PumpActionShotgun_5" },
            { "Rocket Launcher(Common)", "Launcher_Default" },
            { "Rocket Launcher(Uncommon)", "Launcher_Default_2" },
            { "Rocket Launcher(Rare)", "Launcher_Default_3" },
            { "Rocket Launcher(Epic)", "Launcher_Default_4" },
            { "Rocket Launcher(Legendary)", "Launcher_Default_5" },
            { "RecurveBow", "RecurveBow" },
            { "Refined Metal Spear", "Spear_3" },
            { "Shock Grenade", "FragGrenade_Elec" },
            { "Stun Baton", "ElecBaton" },
            { "Single-shot Rifle", "SingleShotRifle" },
            { "Sniper Rifle", "SniperRifle_Default" },
            { "Stone Spear", "Spear" },
            { "Scatter Sphere Launcher", "SphereLauncher" },
            { "Single-shot Sphere Launcher", "SphereLauncher_Once" },
            { "Sword", "Sword" },
            { "Triple Shot Bow", "Bow_triple" },
            { "Wooden Club", "Bat" },
            { "Beam Sword", "BeamSword" },
            { "Katana", "Katana" },
            { "Semi-Auto Rifle(Common)", "SemiAutoRifle" },
            { "Semi-Auto Rifle(Uncommon)", "SemiAutoRifle_2" },
            { "Semi-Auto Rifle(Rare)", "SemiAutoRifle_3" },
            { "Semi-Auto Rifle(Epic)", "SemiAutoRifle_4" },
            { "Semi-Auto Rifle(Legendary)", "SemiAutoRifle_5" },
            { "Semi-Auto Shotgun(Common)", "SemiAutoShotgun" },
            { "Semi-Auto Shotgun(Uncommon)", "SemiAutoShotgun_2" },
            { "Semi-Auto Shotgun(Rare)", "SemiAutoShotgun_3" },
            { "Semi-Auto Shotgun(Epic)", "SemiAutoShotgun_4" },
            { "Semi-Auto Shotgun(Legendary)", "SemiAutoShotgun_5" },
            { "Makeshift Assault Rifle(Common)", "MakeshiftAssaultRifle" },
            { "Makeshift Assault Rifle(Uncommon)", "MakeshiftAssaultRifle_2" },
            { "Makeshift Assault Rifle(Rare)", "MakeshiftAssaultRifle_3" },
            { "Makeshift Assault Rifle(Epic)", "MakeshiftAssaultRifle_4" },
            { "Makeshift Assault Rifle(Legendary)", "MakeshiftAssaultRifle_5" },
            { "Makeshift Shotgun(Common)", "MakeshiftShotgun" },
            { "Makeshift Shotgun(Uncommon)", "MakeshiftShotgun_2" },
            { "Makeshift Shotgun(Rare)", "MakeshiftShotgun_3" },
            { "Makeshift Shotgun(Epic)", "MakeshiftShotgun_4" },
            { "Makeshift Shotgun(Legendary)", "MakeshiftShotgun_5" },
            { "Makeshift Submachine Gun(Uncommon)", "MakeshiftSubmachineGun_2" },
            { "Makeshift Submachine Gun(Rare)", "MakeshiftSubmachineGun_3" },
            { "Makeshift Submachine Gun(Epic)", "MakeshiftSubmachineGun_4" },
            { "Makeshift Submachine Gun(Legendary)", "MakeshiftSubmachineGun_5" },
            { "Laser Gatling Gun(Uncommon)", "LaserGatlingGun_2" },
            { "Laser Gatling Gun(Rare)", "LaserGatlingGun_3" },
            { "Laser Gatling Gun(Epic)", "LaserGatlingGun_4" },
            { "Laser Gatling Gun(Legendary)", "LaserGatlingGun_5" },
            { "Tech Bow(Uncommon)", "SFBow_2" },
            { "Tech Bow(Rare)", "SFBow_3" },
            { "Tech Bow(Epic)", "SFBow_4" },
            { "Tech Bow(Legendary)", "SFBow_5" },
            { "Overheat Rifle", "OverheatRifle" },
            { "Charge Laser Rifle", "ChargeLaserRifle" },
            { "Energy Shotgun", "EnergyShotgun" },
            { "Pal Doping Shot", "PalDopingShot" },
            { "Pal Doping Shot (Uncommon)", "PalDopingShot_2" },
            { "Pal Healing Grenade", "PalHealingGrenade" },
            { "Terra Blade (Epic)", "YakushimaBlade002_4" },
            { "Terra Blade (Legendary)", "YakushimaBlade002_5" },
            { "Terra Prism (Common)", "YakushimaBlade003" },
            { "Terra Prism (Ucommon)", "YakushimaBlade003_1" },
            { "Terra Prism (Rare)", "YakushimaBlade003_2" },
            { "Terra Prism (Epic)", "YakushimaBlade003_3" },
            { "Terra Prism (Legendary)", "YakushimaBlade003_4" },
            { "Terra Prism (Mythic)", "YakushimaBlade003_5" },
            { "Excalibur (Common)", "YakushimaBlade004" },
            { "Excalibur (Uncommon)", "YakushimaBlade004_1" },
            { "Excalibur (Rare)", "YakushimaBlade004_2" },
            { "Excalibur (Epic)", "YakushimaBlade004_3" },
            { "Excalibur (Legendary)", "YakushimaBlade004_4" },
            { "Excalibur (Mythic)", "YakushimaBlade004_5" },
            { "Vortex Beater (Common)", "YakushimaGun001" },
            { "Vortex Beater (Uncommon)", "YakushimaGun001_1" },
            { "Vortex Beater (Rare)", "YakushimaGun001_2" },
            { "Vortex Beater (Epic)", "YakushimaGun001_3" },
            { "Vortex Beater (Legendary)", "YakushimaGun001_4" },
            { "Vortex Beater (Mythic)", "YakushimaGun001_5" }
        }},
        { "Money", {
            { "Diamond", "Diamond" },
            { "Emerald", "Eemerald" },
            { "Gold Coin", "Money" },
            { "Pure Quartz", "Quartz" },
            { "Ruby", "Ruby" },
            { "Sapphire", "Sapphire" }
        }}
    };
}